package com.smartfarm.smartfarm.Config;


import com.smartfarm.smartfarm.entity.Crop;
import com.smartfarm.smartfarm.repositories.CropRepo;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class CropSeeder implements CommandLineRunner {

    private final CropRepo cropRepo;



    @Override
    public void run(String... args) throws Exception {
        if (cropRepo.count() == 0) {
            cropRepo.saveAll(java.util.List.of(
                    Crop.builder()
                            .name("Wheat")
                            .category("Cereal")
                            .idealTempMin(10f)
                            .idealTempMax(25f)
                            .idealHumidityMin(50f)
                            .idealHumidityMax(80f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Oct-Jan")
                            .harvestSeason("Mar-May")
                            .growthDurationDays(120)
                            .popular(true)
                            .description("Staple cereal crop grown in temperate regions.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Rice")
                            .category("Cereal")
                            .idealTempMin(20f)
                            .idealTempMax(35f)
                            .idealHumidityMin(70f)
                            .idealHumidityMax(90f)
                            .soilType("Clay")
                            .waterRequirement("High")
                            .plantingSeason("Jun-Jul")
                            .harvestSeason("Nov-Dec")
                            .growthDurationDays(150)
                            .popular(true)
                            .description("Main staple food crop, requires warm and humid conditions.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Maize")
                            .category("Cereal")
                            .idealTempMin(18f)
                            .idealTempMax(30f)
                            .idealHumidityMin(60f)
                            .idealHumidityMax(80f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Jun-Jul")
                            .harvestSeason("Oct-Nov")
                            .growthDurationDays(120)
                            .popular(true)
                            .description("Versatile cereal crop used for food, feed, and industrial purposes.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Barley")
                            .category("Cereal")
                            .idealTempMin(12f)
                            .idealTempMax(25f)
                            .idealHumidityMin(50f)
                            .idealHumidityMax(75f)
                            .soilType("Loamy")
                            .waterRequirement("Low")
                            .plantingSeason("Oct-Dec")
                            .harvestSeason("Mar-May")
                            .growthDurationDays(110)
                            .popular(false)
                            .description("Used for food, beverages, and fodder.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Sorghum")
                            .category("Cereal")
                            .idealTempMin(20f)
                            .idealTempMax(35f)
                            .idealHumidityMin(40f)
                            .idealHumidityMax(70f)
                            .soilType("Loamy")
                            .waterRequirement("Low")
                            .plantingSeason("Jun-Jul")
                            .harvestSeason("Oct-Nov")
                            .growthDurationDays(120)
                            .popular(false)
                            .description("Drought-resistant cereal used for food and fodder.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Tomato")
                            .category("Vegetable")
                            .idealTempMin(18f)
                            .idealTempMax(27f)
                            .idealHumidityMin(60f)
                            .idealHumidityMax(80f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Mar-Apr")
                            .harvestSeason("Jul-Aug")
                            .growthDurationDays(90)
                            .popular(true)
                            .description("Common vegetable used in salads, sauces, and cooking.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Potato")
                            .category("Vegetable")
                            .idealTempMin(15f)
                            .idealTempMax(22f)
                            .idealHumidityMin(60f)
                            .idealHumidityMax(80f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Oct-Dec")
                            .harvestSeason("Feb-Apr")
                            .growthDurationDays(120)
                            .popular(true)
                            .description("Widely grown tuber crop for food.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Onion")
                            .category("Vegetable")
                            .idealTempMin(15f)
                            .idealTempMax(25f)
                            .idealHumidityMin(55f)
                            .idealHumidityMax(75f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Oct-Dec")
                            .harvestSeason("Mar-May")
                            .growthDurationDays(120)
                            .popular(true)
                            .description("Popular bulb vegetable used in cooking worldwide.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Carrot")
                            .category("Vegetable")
                            .idealTempMin(16f)
                            .idealTempMax(21f)
                            .idealHumidityMin(50f)
                            .idealHumidityMax(75f)
                            .soilType("Sandy")
                            .waterRequirement("Medium")
                            .plantingSeason("Oct-Dec")
                            .harvestSeason("Jan-Mar")
                            .growthDurationDays(90)
                            .popular(false)
                            .description("Root vegetable rich in vitamins and minerals.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Cauliflower")
                            .category("Vegetable")
                            .idealTempMin(15f)
                            .idealTempMax(20f)
                            .idealHumidityMin(55f)
                            .idealHumidityMax(75f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Oct-Dec")
                            .harvestSeason("Jan-Mar")
                            .growthDurationDays(90)
                            .popular(false)
                            .description("Leafy vegetable, used widely in cooking.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Spinach")
                            .category("Vegetable")
                            .idealTempMin(16f)
                            .idealTempMax(24f)
                            .idealHumidityMin(60f)
                            .idealHumidityMax(85f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Sep-Nov")
                            .harvestSeason("Dec-Jan")
                            .growthDurationDays(50)
                            .popular(true)
                            .description("Leafy green vegetable rich in iron and vitamins.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Sugarcane")
                            .category("Cash Crop")
                            .idealTempMin(20f)
                            .idealTempMax(32f)
                            .idealHumidityMin(70f)
                            .idealHumidityMax(90f)
                            .soilType("Clay")
                            .waterRequirement("High")
                            .plantingSeason("Feb-Apr")
                            .harvestSeason("Oct-Dec")
                            .growthDurationDays(360)
                            .popular(true)
                            .description("Major cash crop used for sugar production.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Cotton")
                            .category("Fiber Crop")
                            .idealTempMin(25f)
                            .idealTempMax(35f)
                            .idealHumidityMin(50f)
                            .idealHumidityMax(80f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Apr-Jun")
                            .harvestSeason("Sep-Nov")
                            .growthDurationDays(150)
                            .popular(true)
                            .description("Fiber crop used for textile production.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Sunflower")
                            .category("Oilseed")
                            .idealTempMin(20f)
                            .idealTempMax(30f)
                            .idealHumidityMin(40f)
                            .idealHumidityMax(70f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Feb-Apr")
                            .harvestSeason("Jun-Jul")
                            .growthDurationDays(120)
                            .popular(true)
                            .description("Oilseed crop producing sunflower oil.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Groundnut")
                            .category("Oilseed")
                            .idealTempMin(20f)
                            .idealTempMax(30f)
                            .idealHumidityMin(50f)
                            .idealHumidityMax(70f)
                            .soilType("Sandy Loam")
                            .waterRequirement("Medium")
                            .plantingSeason("Jun-Jul")
                            .harvestSeason("Oct-Nov")
                            .growthDurationDays(120)
                            .popular(true)
                            .description("Legume crop producing peanuts/oil.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Mango")
                            .category("Fruit")
                            .idealTempMin(24f)
                            .idealTempMax(30f)
                            .idealHumidityMin(60f)
                            .idealHumidityMax(85f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Mar-Apr")
                            .harvestSeason("Jun-Jul")
                            .growthDurationDays(150)
                            .popular(true)
                            .description("Popular tropical fruit with sweet flavor.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Banana")
                            .category("Fruit")
                            .idealTempMin(26f)
                            .idealTempMax(32f)
                            .idealHumidityMin(70f)
                            .idealHumidityMax(90f)
                            .soilType("Loamy")
                            .waterRequirement("High")
                            .plantingSeason("Feb-Apr")
                            .harvestSeason("Sep-Dec")
                            .growthDurationDays(180)
                            .popular(true)
                            .description("Widely grown tropical fruit rich in potassium.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Papaya")
                            .category("Fruit")
                            .idealTempMin(25f)
                            .idealTempMax(32f)
                            .idealHumidityMin(65f)
                            .idealHumidityMax(85f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Feb-Apr")
                            .harvestSeason("Jul-Oct")
                            .growthDurationDays(150)
                            .popular(false)
                            .description("Fast-growing tropical fruit.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Guava")
                            .category("Fruit")
                            .idealTempMin(20f)
                            .idealTempMax(30f)
                            .idealHumidityMin(60f)
                            .idealHumidityMax(80f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Jan-Mar")
                            .harvestSeason("Jun-Aug")
                            .growthDurationDays(120)
                            .popular(false)
                            .description("Tropical fruit rich in vitamin C.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Pomegranate")
                            .category("Fruit")
                            .idealTempMin(20f)
                            .idealTempMax(35f)
                            .idealHumidityMin(50f)
                            .idealHumidityMax(70f)
                            .soilType("Loamy")
                            .waterRequirement("Low")
                            .plantingSeason("Feb-Apr")
                            .harvestSeason("Aug-Oct")
                            .growthDurationDays(150)
                            .popular(false)
                            .description("Fruit crop with high medicinal value.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Watermelon")
                            .category("Fruit")
                            .idealTempMin(25f)
                            .idealTempMax(35f)
                            .idealHumidityMin(60f)
                            .idealHumidityMax(85f)
                            .soilType("Sandy Loam")
                            .waterRequirement("High")
                            .plantingSeason("Feb-Apr")
                            .harvestSeason("Jun-Aug")
                            .growthDurationDays(90)
                            .popular(true)
                            .description("Summer fruit rich in water and vitamins.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Cucumber")
                            .category("Vegetable")
                            .idealTempMin(18f)
                            .idealTempMax(30f)
                            .idealHumidityMin(60f)
                            .idealHumidityMax(80f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Feb-Apr")
                            .harvestSeason("Jun-Jul")
                            .growthDurationDays(60)
                            .popular(true)
                            .description("Crisp vegetable used in salads and cooking.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Chilli")
                            .category("Vegetable")
                            .idealTempMin(20f)
                            .idealTempMax(30f)
                            .idealHumidityMin(50f)
                            .idealHumidityMax(75f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Jan-Mar")
                            .harvestSeason("May-Jul")
                            .growthDurationDays(90)
                            .popular(false)
                            .description("Spicy vegetable used worldwide.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Okra")
                            .category("Vegetable")
                            .idealTempMin(20f)
                            .idealTempMax(32f)
                            .idealHumidityMin(50f)
                            .idealHumidityMax(75f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Mar-Apr")
                            .harvestSeason("Jul-Sep")
                            .growthDurationDays(90)
                            .popular(false)
                            .description("Also known as ladyfinger, used in cooking.")
                            .imageUrl("")
                            .build(),

                    Crop.builder()
                            .name("Peas")
                            .category("Vegetable")
                            .idealTempMin(10f)
                            .idealTempMax(25f)
                            .idealHumidityMin(50f)
                            .idealHumidityMax(75f)
                            .soilType("Loamy")
                            .waterRequirement("Medium")
                            .plantingSeason("Oct-Dec")
                            .harvestSeason("Jan-Mar")
                            .growthDurationDays(60)
                            .popular(false)
                            .description("Cool-season legume vegetable.")
                            .imageUrl("")
                            .build()
            ));
        }
    }
}
